### ISSUE TITLE
Expand to Germany/international?

### ISSUE THREAD

**Issue by Malwine** [Malwine/support-juniors#10]
@bitboxer @andrecedik and everybody that is interested:
After the latest PR https://github.com/Malwine/juniors-in-berlin/pull/9 from Pilot Bootcamp and a [tweet](https://twitter.com/AndreCedik/status/559822156423380992) from André from Hamburg I thought about whether we should make the list more open to other German cities or even international.
It could look like this:
- Dawanda [Berlin/GER]  

But I am not fully convinced whether this makes sense.

**Comment by sharnik** [comment]
+1, I'd be happy to see it take off in Barcelona (also willing to help)

**Comment by Malwine** [comment]
Cool let's do this. I will contact you again :)

**Comment by Malwine** [comment]
@sharnik I changed wording in the readme. Now you can add companies in Barcelona too.
